// <auto-generated />
using APIpetshop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIpetshop.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240530051338_initia")]
    partial class initia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIpetshop.Models.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("productos");

                    b.HasData(
                        new
                        {
                            id = 1001,
                            name = "Cool Watch",
                            price = "99",
                            quantity = "44"
                        },
                        new
                        {
                            id = 1002,
                            name = "Diving Watch",
                            price = "89",
                            quantity = "89"
                        },
                        new
                        {
                            id = 1003,
                            name = "Dress Watch",
                            price = "85",
                            quantity = "66"
                        },
                        new
                        {
                            id = 1004,
                            name = "Military Watch",
                            price = "99",
                            quantity = "45"
                        },
                        new
                        {
                            id = 1005,
                            name = "Wrist Watch",
                            price = "85",
                            quantity = "75"
                        },
                        new
                        {
                            id = 1006,
                            name = "Army Watch",
                            price = "99",
                            quantity = "50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
